# 01_01_Data Collection Infrabel

In [1]:
from pathlib import Path
    
import pandas as pd

import infrabel_punctuality as ip

In [2]:
DATA_DIR = Path("../data/raw/")

DATA_INT_DIR = Path("../data/intermediate/")

# Table of Contents  

- [1. Dictionaries of Datasets to Ingest from Infrabel Open Data](#1-dictionaries-of-datasets-to-ingest-from-infrabel-open-data)
    - [1.1. First Dictionary of Datasets](#11-first-dictionary-of-datasets)
    - [1.2. Second Dictionary of Datasets - Punctuality Raw Data](#12-second-dictionary-of-datasets---punctuality-raw-data)  
    
- [2. Infrabel Datasets Ingestion](#2-infrabel-datasets-ingestion)
    - [2.1. Download Configuration and Execution](#21-download-configuration-and-execution)
    - [2.2. Download Verification - Spot Check on Sample Files](#22-download-verification---spot-check-on-sample-files)  

- [3. Concatenation of 24 Monthly Datasets into a Single Raw Punctuality Dataset](#3-concatenation-of-24-monthly-datasets-into-a-single-raw-punctuality-dataset)
    - [3.1. Concatenation into Yearly Punctuality Datasets](#31-concatenation-into-yearly-punctuality-datasets)
    - [3.2. Export Verification of the Yearly Punctuality Datasets](#32-export-verification-of-the-yearly-punctuality-datasets)
    - [3.3. Concatenation of `punctuality_raw`](#33-concatenation-of-punctuality_raw)
    
- [4. Export to Silver layer](#4-export-to-silver-layer)

## 1. Dictionaries of Datasets to Ingest from Infrabel Open Data

### 1.1. First Dictionary of Datasets

**First dictionary of datasets** `datasets1`:  

* `operational_pts_railway_raw`: the future `Dim_Station`.  

* `monthly_punctuality_agg`: monthly aggregated Infrabel punctuality measures used as a future **benchmark**. This benchmark will not be loaded into the data warehouse but will be used directly in Power BI for a **final comparaison with the recalculated punctuality measures**.

In [3]:

datasets_1 = {
    "operational_pts_railway_raw" : "https://opendata.infrabel.be/api/explore/v2.1/catalog/datasets/operationele-punten-van-het-netwerk/exports/parquet?lang=en&timezone=Europe%2FBerlin",
    "monthly_punctuality_agg" : "https://opendata.infrabel.be/api/explore/v2.1/catalog/datasets/nationale-stiptheid-per-maand/exports/parquet?lang=fr&timezone=Europe%2FBerlin"
    }

### 1.2. Second Dictionary of Datasets - Punctuality Raw Data

**Second dictionary of datasets** `datasets2`: 

* A dictionary of **24 monthly datasets of raw punctuality data**. They will be ingested and concatenated into the `punctuality_raw` dataset.  

* These monthly datasets are available on the Infrabel Open Data portal as `.csv` files.  

* In the cell below, the dictionary keys and URLs are generated automatically from a year-month loop, avoiding hardcoding 24 key-value pairs manually.

In [4]:
years = [2024, 2025]
months = [f"{m:02d}" for m in range(1, 13)]

datasets_2 = {}

for year in years:
    for month in months:
        key = f"punctuality_raw_{month}{year}"

        url = f"https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_{year}{month}.csv"

        datasets_2[key] = url

for key in datasets_2:
    print(f"{key} : {url} \n")

punctuality_raw_012024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_022024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_032024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_042024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_052024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_062024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_072024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_082024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_092024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_102024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_112024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_122024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_012025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_022025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_032025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_042025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_052025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_062025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_072025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_082025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_092025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_102025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_112025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_122025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

## 2. Infrabel Datasets Ingestion

### 2.1. Download Configuration and Execution

In [5]:
ip.run_download(datasets_1, output_dir=DATA_DIR)

Downloading datasets:   0%|          | 0.00/2.00 [00:00<?, ?file/s]

Starting download : operational_pts_railway_raw

Downloading datasets:  50%|█████     | 1.00/2.00 [00:04<00:04, 4.09s/file]

operational_pts_railway_raw downloaded to ..\data\raw\operational_pts_railway_raw.parquet

Starting download : monthly_punctuality_agg

Downloading datasets: 100%|██████████| 2.00/2.00 [00:06<00:00, 3.06s/file]

monthly_punctuality_agg downloaded to ..\data\raw\monthly_punctuality_agg.parquet

**⚠️ Warning**: 
* The cell below downloads 24 raw data files from the Infrabel Open Data portal. Depending on your internet connection and local configuration, this may take more than **30 minutes**. 

* The line of code that triggers the download is **commented out for safety**. Uncomment it only if you want to start the download.

In [ ]:
#ip.run_download(
#    datasets_2, 
#    output_dir=DATA_DIR, 
#    file_type="csv", 
#    registry_name="manifest_punctuality_raw.txt"
#    )

Downloading datasets:   0%|          | 0.00/24.0 [00:00<?, ?file/s]

Starting download : punctuality_raw_012024

Downloading datasets:   4%|▍         | 1.00/24.0 [01:14<28:23, 74.1s/file]

punctuality_raw_012024 downloaded to ..\data\raw\punctuality_raw_012024.csv

Starting download : punctuality_raw_022024

Downloading datasets:   8%|▊         | 2.00/24.0 [02:29<27:26, 74.9s/file]

punctuality_raw_022024 downloaded to ..\data\raw\punctuality_raw_022024.csv

Starting download : punctuality_raw_032024

Downloading datasets:  12%|█▎        | 3.00/24.0 [04:05<29:39, 84.7s/file]

punctuality_raw_032024 downloaded to ..\data\raw\punctuality_raw_032024.csv

Starting download : punctuality_raw_042024

Downloading datasets:  17%|█▋        | 4.00/24.0 [05:36<28:59, 87.0s/file]

punctuality_raw_042024 downloaded to ..\data\raw\punctuality_raw_042024.csv

Starting download : punctuality_raw_052024

Downloading datasets:  21%|██        | 5.00/24.0 [07:10<28:23, 89.7s/file]

punctuality_raw_052024 downloaded to ..\data\raw\punctuality_raw_052024.csv

Starting download : punctuality_raw_062024

Downloading datasets:  25%|██▌       | 6.00/24.0 [08:27<25:36, 85.4s/file]

punctuality_raw_062024 downloaded to ..\data\raw\punctuality_raw_062024.csv

Starting download : punctuality_raw_072024

Downloading datasets:  29%|██▉       | 7.00/24.0 [09:53<24:12, 85.5s/file]

punctuality_raw_072024 downloaded to ..\data\raw\punctuality_raw_072024.csv

Starting download : punctuality_raw_082024

Downloading datasets:  33%|███▎      | 8.00/24.0 [11:26<23:26, 87.9s/file]

punctuality_raw_082024 downloaded to ..\data\raw\punctuality_raw_082024.csv

Starting download : punctuality_raw_092024

Downloading datasets:  38%|███▊      | 9.00/24.0 [12:43<21:04, 84.3s/file]

punctuality_raw_092024 downloaded to ..\data\raw\punctuality_raw_092024.csv

Starting download : punctuality_raw_102024

Downloading datasets:  42%|████▏     | 10.0/24.0 [14:20<20:39, 88.5s/file]

punctuality_raw_102024 downloaded to ..\data\raw\punctuality_raw_102024.csv

Starting download : punctuality_raw_112024

Downloading datasets:  46%|████▌     | 11.0/24.0 [15:38<18:29, 85.3s/file]

punctuality_raw_112024 downloaded to ..\data\raw\punctuality_raw_112024.csv

Starting download : punctuality_raw_122024

Downloading datasets:  50%|█████     | 12.0/24.0 [16:35<15:18, 76.6s/file]

punctuality_raw_122024 downloaded to ..\data\raw\punctuality_raw_122024.csv

Starting download : punctuality_raw_012025

Downloading datasets:  54%|█████▍    | 13.0/24.0 [17:53<14:05, 76.8s/file]

punctuality_raw_012025 downloaded to ..\data\raw\punctuality_raw_012025.csv

Starting download : punctuality_raw_022025

Downloading datasets:  58%|█████▊    | 14.0/24.0 [18:58<12:12, 73.3s/file]

punctuality_raw_022025 downloaded to ..\data\raw\punctuality_raw_022025.csv

Starting download : punctuality_raw_032025

Downloading datasets:  62%|██████▎   | 15.0/24.0 [20:14<11:08, 74.3s/file]

punctuality_raw_032025 downloaded to ..\data\raw\punctuality_raw_032025.csv

Starting download : punctuality_raw_042025

Downloading datasets:  67%|██████▋   | 16.0/24.0 [21:23<09:41, 72.7s/file]

punctuality_raw_042025 downloaded to ..\data\raw\punctuality_raw_042025.csv

Starting download : punctuality_raw_052025

Downloading datasets:  71%|███████   | 17.0/24.0 [22:45<08:48, 75.6s/file]

punctuality_raw_052025 downloaded to ..\data\raw\punctuality_raw_052025.csv

Starting download : punctuality_raw_062025

Downloading datasets:  75%|███████▌  | 18.0/24.0 [24:13<07:55, 79.2s/file]

punctuality_raw_062025 downloaded to ..\data\raw\punctuality_raw_062025.csv

Starting download : punctuality_raw_072025

Downloading datasets:  79%|███████▉  | 19.0/24.0 [25:31<06:33, 78.8s/file]

punctuality_raw_072025 downloaded to ..\data\raw\punctuality_raw_072025.csv

Starting download : punctuality_raw_082025

Downloading datasets:  83%|████████▎ | 20.0/24.0 [26:49<05:14, 78.7s/file]

punctuality_raw_082025 downloaded to ..\data\raw\punctuality_raw_082025.csv

Starting download : punctuality_raw_092025

Downloading datasets:  88%|████████▊ | 21.0/24.0 [28:25<04:10, 83.7s/file]

punctuality_raw_092025 downloaded to ..\data\raw\punctuality_raw_092025.csv

Starting download : punctuality_raw_102025

Downloading datasets:  92%|█████████▏| 22.0/24.0 [29:55<02:51, 85.7s/file]

punctuality_raw_102025 downloaded to ..\data\raw\punctuality_raw_102025.csv

Starting download : punctuality_raw_112025

Downloading datasets:  96%|█████████▌| 23.0/24.0 [31:26<01:27, 87.2s/file]

punctuality_raw_112025 downloaded to ..\data\raw\punctuality_raw_112025.csv

Starting download : punctuality_raw_122025

Downloading datasets: 100%|██████████| 24.0/24.0 [33:32<00:00, 83.9s/file]

punctuality_raw_122025 downloaded to ..\data\raw\punctuality_raw_122025.csv

### 2.2. Download Verification - Spot Check on Sample Files

In [7]:
ope_pts = pd.read_parquet(DATA_DIR / "operational_pts_railway_raw.parquet")
ope_pts.head()

,geo_point_2d,geo_shape,ptcarid,taftapcode,symbolicname,shortnamefrench,shortnamedutch,longnamefrench,longnamedutch,commercialshortnamefrench,commercialshortnamedutch,commercialmiddlenamefrench,commercialmiddlenamedutch,commerciallongnamefrench,commerciallongnamedutch,class_en
0,b'\x01\x01\x00\x00\x00dp\xfc\x92;2\x10@\xfbrfv...,b'\x01\x01\x00\x00\x00dp\xfc\x92;2\x10@\xfbrfv...,7,BE00007,FLSO,AALST-OOST,AALST-OOST,AALST-OOST,AALST-OOST,Alost-Est,Aalst-Oost,Alost-Est,Aalst-Oost,Alost-Est,Aalst-Oost,Station
1,b'\x01\x01\x00\x00\x00x{\xff35\x95\x0b@Vno\x1a...,b'\x01\x01\x00\x00\x00x{\xff35\x95\x0b@Vno\x1a...,8,BE00008,FLT,AALTER,AALTER,AALTER,AALTER,Aalter,Aalter,Aalter,Aalter,Aalter,Aalter,Station
2,b'\x01\x01\x00\x00\x00\x0f7k\x94wK\x13@\xc0\xc...,b'\x01\x01\x00\x00\x00\x0f7k\x94wK\x13@\xc0\xc...,9,BE00009,FRST,AARSCHOT,AARSCHOT,AARSCHOT,AARSCHOT,Aarschot,Aarschot,Aarschot,Aarschot,Aarschot,Aarschot,Station
3,b'\x01\x01\x00\x00\x00z\xbf\xb6#\xd3X\x0b@\xe6...,b'\x01\x01\x00\x00\x00z\xbf\xb6#\xd3X\x0b@\xe6...,10,BE00010,FAR,AARSELE,AARSELE,AARSELE,AARSELE,Aarsele,Aarsele,Aarsele,Aarsele,Aarsele,Aarsele,Stop in open track
4,b'\x01\x01\x00\x00\x00\xdb~\xf4x\xb1\xc6\x0e@\...,b'\x01\x01\x00\x00\x00\xdb~\xf4x\xb1\xc6\x0e@\...,12,BE00012,FXA,ACREN,ACREN,ACREN,ACREN,Acren,Acren,Acren,Acren,Acren,Acren,Stop in open track

In [8]:
punctuality_monthly_agg = pd.read_parquet(DATA_DIR / "monthly_punctuality_agg.parquet")
punctuality_monthly_agg.head()

,jaar,maand,regelmaat,tel,reg,min_rt,regelmaatneutralisatie,reg_neutr,tel_ytd,reg_ytd,regelmaat_ytd
0,2016-01-01,2016-02-01,90.875745,102233,92905,203292,95.165944,97291,202266,182804,90.378017
1,2016-01-01,2016-04-01,90.567481,99369,89996,195684,96.484819,95876,406313,367793,90.519624
2,2017-01-01,2017-06-01,87.280144,106888,93292,273664,92.029040,98368,636751,568164,89.228600
3,2017-01-01,2017-10-01,83.560281,107514,89839,330432,89.917592,96674,1057998,942591,89.091945
4,2018-01-01,2018-02-01,87.254892,101945,88952,250288,90.771494,92537,216206,190165,87.955468

In [9]:
punctuality_monthly_raw = pd.read_csv(DATA_DIR / "punctuality_raw_012024.csv")
punctuality_monthly_raw.head()

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,THOP1_COD,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,...,DELAY_ARR,DELAY_DEP,CIRC_TYP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP
0,01JAN2024,1813,IC 02,SNCB/NMBS,929,NaN,50A,NaN,13:09:42,NaN,...,NaN,42.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTENDE,NaN,NaN,01JAN2024,NaN,01JAN2024
1,01JAN2024,1813,IC 02,SNCB/NMBS,210,=,50A,13:22:17,13:25:20,13:22:00,...,17.0,20.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BRUGGE,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
2,01JAN2024,1813,IC 02,SNCB/NMBS,931,D,50A,13:29:18,13:29:18,13:28:00,...,78.0,78.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTKAMP,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
3,01JAN2024,1813,IC 02,SNCB/NMBS,127,P,50A,13:31:59,13:31:59,13:31:00,...,59.0,59.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BEERNEM,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
4,01JAN2024,1813,IC 02,SNCB/NMBS,797,D,50A,13:33:57,13:33:57,13:33:00,...,57.0,57.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,MARIA-AALTER,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024

## 3. Concatenation of 24 Monthly Datasets into a Single Raw Punctuality Dataset

* The 24 monthly raw datasets are concatenated first into **two yearly datasets**, then into **a single dataset**.  

* This dataset will serve as the source for the data warehouse's `fact_punctuality`.

### 3.1. Concatenation into Yearly Punctuality Datasets

The monthly punctuality datasets paths are collected into two yearly lists - `files_2024` and `files_2025` - then sorted.

In [10]:
files_2024 = list(DATA_DIR.glob("punctuality_raw_*2024.csv"))
files_2024.sort()

files_2025 = list(DATA_DIR.glob("punctuality_raw_*2025.csv"))
files_2025.sort()

* The twelve 2024 monthly datasets are concatenated into a single DataFrame - `punctuality_raw_2024`.  

* `punctuality_raw_2024` is exported as a `.parquet` file.

* `punctuality_raw_2024` is deleted to free RAM.

* Then, the same operations are executed for the twelve 2025 monthly datasets and a `punctuality_raw_2025` file is exported.

**⚠️ Warning**: The cell below may take **3 to 4 minutes** to execute.

In [11]:
punctuality_raw_2024 = pd.concat(
    (pd.read_csv(f) for f in files_2024),
    ignore_index=True
)
punctuality_raw_2024.head()

punctuality_raw_2024.to_parquet(DATA_INT_DIR / "punctuality_raw_2024.parquet")

del punctuality_raw_2024

df_punctuality_raw_2025 = pd.concat(
    (pd.read_csv(f) for f in files_2025),
    ignore_index=True
)
df_punctuality_raw_2025.head()

df_punctuality_raw_2025.to_parquet(DATA_INT_DIR / "punctuality_raw_2025.parquet")

del df_punctuality_raw_2025

### 3.2. Export Verification of the Yearly Punctuality Datasets

In [12]:
punct_2024 = pd.read_parquet(DATA_INT_DIR / "punctuality_raw_2024.parquet")
punct_2024.head()

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,THOP1_COD,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,...,DELAY_ARR,DELAY_DEP,CIRC_TYP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP
0,01JAN2024,1813,IC 02,SNCB/NMBS,929,NaN,50A,NaN,13:09:42,NaN,...,NaN,42.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTENDE,NaN,NaN,01JAN2024,NaN,01JAN2024
1,01JAN2024,1813,IC 02,SNCB/NMBS,210,=,50A,13:22:17,13:25:20,13:22:00,...,17.0,20.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BRUGGE,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
2,01JAN2024,1813,IC 02,SNCB/NMBS,931,D,50A,13:29:18,13:29:18,13:28:00,...,78.0,78.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTKAMP,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
3,01JAN2024,1813,IC 02,SNCB/NMBS,127,P,50A,13:31:59,13:31:59,13:31:00,...,59.0,59.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BEERNEM,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
4,01JAN2024,1813,IC 02,SNCB/NMBS,797,D,50A,13:33:57,13:33:57,13:33:00,...,57.0,57.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,MARIA-AALTER,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024

In [13]:
punct_2025 = pd.read_parquet(DATA_INT_DIR / "punctuality_raw_2025.parquet")
punct_2025.head()

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,THOP1_COD,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,...,DELAY_DEP,CIRC_TYP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,OP1_COD
0,01JAN2025,3117,IC 31,SNCB/NMBS,259,NaN,124,NaN,17:05:40,NaN,...,40.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,CHARLEROI-CENTRAL,NaN,NaN,01JAN2025,NaN,01JAN2025,NaN
1,01JAN2025,3117,IC 31,SNCB/NMBS,791,=,124,17:09:50,17:11:27,17:10:00,...,27.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,MARCHIENNE-AU-PONT,124,01JAN2025,01JAN2025,01JAN2025,01JAN2025,NaN
2,01JAN2025,3117,IC 31,SNCB/NMBS,1018,P,124,17:14:29,17:14:29,17:14:00,...,29.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,ROUX,124,01JAN2025,01JAN2025,01JAN2025,01JAN2025,NaN
3,01JAN2025,3117,IC 31,SNCB/NMBS,286,D,124,17:15:39,17:15:39,17:15:00,...,39.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,COURCELLES-MOTTE,124,01JAN2025,01JAN2025,01JAN2025,01JAN2025,NaN
4,01JAN2025,3117,IC 31,SNCB/NMBS,768,=,124,17:19:02,17:20:18,17:19:00,...,18.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,LUTTRE,124,01JAN2025,01JAN2025,01JAN2025,01JAN2025,NaN

### 3.3. Concatenation of `punctuality_raw`

The two yearly raw punctuality datasets are concatenated into a single `punctuality_raw` DataFrame, then exported as a `.parquet` file in the next section.

In [14]:
punctuality_raw = pd.concat([punct_2024, punct_2025], ignore_index=True)

## 4. Export to Silver Layer

**⚠️ Warning**: The cell below may take **2 to 3 minutes** to execute.

In [15]:
punctuality_raw.to_parquet(DATA_INT_DIR / "punctuality_raw.parquet")

del punctuality_raw

In [16]:
df_to_check = pd.read_parquet(DATA_INT_DIR / "punctuality_raw.parquet")
df_to_check.head()

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,THOP1_COD,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,...,DELAY_DEP,CIRC_TYP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,OP1_COD
0,01JAN2024,1813,IC 02,SNCB/NMBS,929,NaN,50A,NaN,13:09:42,NaN,...,42.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTENDE,NaN,NaN,01JAN2024,NaN,01JAN2024,NaN
1,01JAN2024,1813,IC 02,SNCB/NMBS,210,=,50A,13:22:17,13:25:20,13:22:00,...,20.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BRUGGE,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024,NaN
2,01JAN2024,1813,IC 02,SNCB/NMBS,931,D,50A,13:29:18,13:29:18,13:28:00,...,78.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTKAMP,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024,NaN
3,01JAN2024,1813,IC 02,SNCB/NMBS,127,P,50A,13:31:59,13:31:59,13:31:00,...,59.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BEERNEM,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024,NaN
4,01JAN2024,1813,IC 02,SNCB/NMBS,797,D,50A,13:33:57,13:33:57,13:33:00,...,57.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,MARIA-AALTER,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024,NaN