# 01_01_Collecte des données de l'Open Data Infrabel #

In [1]:
import infrabel_punctuality as ip
import pandas as pd
from pathlib import Path

## 1. Dictionnaires des datasets à importer depuis l'Open Data d'Infrabel ##

### 1.1. Dictionnaie de datasets 1 ###

- operational_pts_railway_raw : future dimension gare,
- monthly_punctuality_agg : mesures agrégées mensuelles de ponctualité d'Infrabel qui serviront à une comparaison finale avec les mesures de ponctualité recalculées,
- most_important_incidents_punctuality_sum : future table de contexte sur les incidents (agrégée par jour et par incident et filtrée selon la règle SUM(Delay_min) >= 1000).

In [30]:

datasets_1 = {
    "operational_pts_railway_raw" : "https://opendata.infrabel.be/api/explore/v2.1/catalog/datasets/operationele-punten-van-het-netwerk/exports/parquet?lang=en&timezone=Europe%2FBerlin",
    "monthly_punctuality_agg" : "https://opendata.infrabel.be/api/explore/v2.1/catalog/datasets/belangrijkste-incidenten/exports/parquet?lang=fr&timezone=Europe%2FBerlin",
    "most_important_incidents_punctuality_sum" : "https://opendata.infrabel.be/api/explore/v2.1/catalog/datasets/belangrijkste-incidenten/exports/parquet?lang=fr&timezone=Europe%2FBerlin"
}

### 1.2. Dictionnaire de datasets 2 : données brutes de ponctualité ###

- Dictionnaire de datasets 2 : le dictionnaire des données de ponctualité brute (future table de fait)
    - 24 datasets mensuels de ponctualité

Les données brutes de ponctualité sont téléchargeables sur le portail Open Data d'Infrabel sous la forme de fichiers .csv. <br>
Chaque fichier reprend les données brutes d'un mois. <br>
La fonction ci-dessous va permettre de télécharger les 24 fichiers de ponctualité brute des années 2024 et 2025.

In [14]:
years = [2024, 2025]
months = [f"{m:02d}" for m in range(1, 13)]

datasets_2 = {}

for year in years:
    for month in months:
        key = f"punctuality_raw_{month}{year}"

        url = f"https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_{year}{month}.csv"

        datasets_2[key] = url

for key in datasets_2:
    print(f"{key} : {url} \n")

punctuality_raw_012024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_022024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_032024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_042024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_052024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_062024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_072024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_082024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_092024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_102024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_112024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_122024 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_012025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_022025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_032025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_042025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_052025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_062025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_072025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_082025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_092025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_102025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_112025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

punctuality_raw_122025 : https://fr.ftp.opendatasoft.com/infrabel/PunctualityHistory/Data_raw_punctuality_202512.csv

## 2. Téléchargement des datasets ##

### 2.1. Configuration des paramètres et téléchargement ###

In [33]:
# Configurer le chemin
DATA_DIR = Path("../data/raw/")

ip.run_download(datasets_1, output_dir=DATA_DIR)

Downloading datasets:   0%|          | 0.00/3.00 [00:00<?, ?file/s]

Début du téléchargement : operational_pts_railway_raw

Downloading datasets:  33%|███▎      | 1.00/3.00 [00:01<00:03, 1.74s/file]

operational_pts_railway_raw téléchargé dans ..\data\raw\operational_pts_railway_raw.parquet
Début du téléchargement : monthly_punctuality_agg

Downloading datasets:  67%|██████▋   | 2.00/3.00 [00:02<00:01, 1.43s/file]

monthly_punctuality_agg téléchargé dans ..\data\raw\monthly_punctuality_agg.parquet
Début du téléchargement : most_important_incidents_punctuality_sum

Downloading datasets: 100%|██████████| 3.00/3.00 [00:04<00:00, 1.50s/file]

most_important_incidents_punctuality_sum téléchargé dans ..\data\raw\most_important_incidents_punctuality_sum.parquet

**Warning**<br>
La cellule suivante exécute le téléchargement de 24 fichiers de données brutes depuis le portail Open Data d'Infrabel.<br>
Le téléchargement prend environ **1 heure** en fonction de votre connexion Internet.<br>

La ligne de code qui exécute le téléchargement est commentée par sécurité.<br>
Décommentez la ligne 3 si vous voulez lancer le téléchargement.<br>

In [ ]:
# Configuration du nom du manifeste et du type de fichier

# ip.run_download(datasets_2, output_dir=DATA_DIR, file_type="csv", registry_name="manifest_punctuality_raw.txt")

Downloading datasets:   0%|          | 0.00/24.0 [00:00<?, ?file/s]

Début du téléchargement : punctuality_raw_012024

Downloading datasets:   4%|▍         | 1.00/24.0 [01:49<42:05, 110s/file]

punctuality_raw_012024 téléchargé dans ..\data\raw\punctuality_raw_012024.csv
Début du téléchargement : punctuality_raw_022024

Downloading datasets:   8%|▊         | 2.00/24.0 [04:12<47:20, 129s/file]

punctuality_raw_022024 téléchargé dans ..\data\raw\punctuality_raw_022024.csv
Début du téléchargement : punctuality_raw_032024

Downloading datasets:  12%|█▎        | 3.00/24.0 [07:45<58:33, 167s/file]

punctuality_raw_032024 téléchargé dans ..\data\raw\punctuality_raw_032024.csv
Début du téléchargement : punctuality_raw_042024

Downloading datasets:  17%|█▋        | 4.00/24.0 [10:59<59:18, 178s/file]

punctuality_raw_042024 téléchargé dans ..\data\raw\punctuality_raw_042024.csv
Début du téléchargement : punctuality_raw_052024

Downloading datasets:  21%|██        | 5.00/24.0 [13:46<55:09, 174s/file]

punctuality_raw_052024 téléchargé dans ..\data\raw\punctuality_raw_052024.csv
Début du téléchargement : punctuality_raw_062024

Downloading datasets:  25%|██▌       | 6.00/24.0 [16:20<50:06, 167s/file]

punctuality_raw_062024 téléchargé dans ..\data\raw\punctuality_raw_062024.csv
Début du téléchargement : punctuality_raw_072024

Downloading datasets:  29%|██▉       | 7.00/24.0 [19:54<51:43, 183s/file]

punctuality_raw_072024 téléchargé dans ..\data\raw\punctuality_raw_072024.csv
Début du téléchargement : punctuality_raw_082024

Downloading datasets:  33%|███▎      | 8.00/24.0 [22:36<46:53, 176s/file]

punctuality_raw_082024 téléchargé dans ..\data\raw\punctuality_raw_082024.csv
Début du téléchargement : punctuality_raw_092024

Downloading datasets:  38%|███▊      | 9.00/24.0 [25:15<42:38, 171s/file]

punctuality_raw_092024 téléchargé dans ..\data\raw\punctuality_raw_092024.csv
Début du téléchargement : punctuality_raw_102024

Downloading datasets:  42%|████▏     | 10.0/24.0 [27:51<38:45, 166s/file]

punctuality_raw_102024 téléchargé dans ..\data\raw\punctuality_raw_102024.csv
Début du téléchargement : punctuality_raw_112024

Downloading datasets:  46%|████▌     | 11.0/24.0 [31:37<39:57, 184s/file]

punctuality_raw_112024 téléchargé dans ..\data\raw\punctuality_raw_112024.csv
Début du téléchargement : punctuality_raw_122024

Downloading datasets:  50%|█████     | 12.0/24.0 [35:29<39:48, 199s/file]

punctuality_raw_122024 téléchargé dans ..\data\raw\punctuality_raw_122024.csv
Début du téléchargement : punctuality_raw_012025

Downloading datasets:  54%|█████▍    | 13.0/24.0 [38:25<35:12, 192s/file]

punctuality_raw_012025 téléchargé dans ..\data\raw\punctuality_raw_012025.csv
Début du téléchargement : punctuality_raw_022025

Downloading datasets:  58%|█████▊    | 14.0/24.0 [41:11<30:41, 184s/file]

punctuality_raw_022025 téléchargé dans ..\data\raw\punctuality_raw_022025.csv
Début du téléchargement : punctuality_raw_032025

Downloading datasets:  62%|██████▎   | 15.0/24.0 [43:26<25:24, 169s/file]

punctuality_raw_032025 téléchargé dans ..\data\raw\punctuality_raw_032025.csv
Début du téléchargement : punctuality_raw_042025

Downloading datasets:  67%|██████▋   | 16.0/24.0 [45:59<21:56, 165s/file]

punctuality_raw_042025 téléchargé dans ..\data\raw\punctuality_raw_042025.csv
Début du téléchargement : punctuality_raw_052025

Downloading datasets:  71%|███████   | 17.0/24.0 [48:29<18:39, 160s/file]

punctuality_raw_052025 téléchargé dans ..\data\raw\punctuality_raw_052025.csv
Début du téléchargement : punctuality_raw_062025

Downloading datasets:  75%|███████▌  | 18.0/24.0 [51:17<16:14, 162s/file]

punctuality_raw_062025 téléchargé dans ..\data\raw\punctuality_raw_062025.csv
Début du téléchargement : punctuality_raw_072025

Downloading datasets:  79%|███████▉  | 19.0/24.0 [53:56<13:27, 161s/file]

punctuality_raw_072025 téléchargé dans ..\data\raw\punctuality_raw_072025.csv
Début du téléchargement : punctuality_raw_082025

Downloading datasets:  83%|████████▎ | 20.0/24.0 [56:00<10:01, 150s/file]

punctuality_raw_082025 téléchargé dans ..\data\raw\punctuality_raw_082025.csv
Début du téléchargement : punctuality_raw_092025

Downloading datasets:  88%|████████▊ | 21.0/24.0 [59:27<08:21, 167s/file]

punctuality_raw_092025 téléchargé dans ..\data\raw\punctuality_raw_092025.csv
Début du téléchargement : punctuality_raw_102025

Downloading datasets:  92%|█████████▏| 22.0/24.0 [1:01:32<05:09, 155s/file]

punctuality_raw_102025 téléchargé dans ..\data\raw\punctuality_raw_102025.csv
Début du téléchargement : punctuality_raw_112025

Downloading datasets:  96%|█████████▌| 23.0/24.0 [1:03:57<02:31, 152s/file]

punctuality_raw_112025 téléchargé dans ..\data\raw\punctuality_raw_112025.csv
Début du téléchargement : punctuality_raw_122025

Downloading datasets: 100%|██████████| 24.0/24.0 [1:07:32<00:00, 169s/file]

punctuality_raw_122025 téléchargé dans ..\data\raw\punctuality_raw_122025.csv

### 2.2. Vérification du téléchargement par lecture d'un fichier ###

In [34]:
df = pd.read_parquet(DATA_DIR / "operational_pts_railway_raw.parquet")
df.head()

,geo_point_2d,geo_shape,ptcarid,taftapcode,symbolicname,shortnamefrench,shortnamedutch,longnamefrench,longnamedutch,commercialshortnamefrench,commercialshortnamedutch,commercialmiddlenamefrench,commercialmiddlenamedutch,commerciallongnamefrench,commerciallongnamedutch,classification,class_en,class_fr
0,b'\x01\x01\x00\x00\x00\x13\x11\xbf\xc37\xfd\x1...,b'\x01\x01\x00\x00\x00\x13\x11\xbf\xc37\xfd\x1...,443,BE00443,FKGLF,GENK-ZD-FORD,GENK-ZD-FORD,GENK-ZUID-L.O.-FORD,GENK-ZUID-L.O.-FORD,Genk-Zd-Ford,Genk-Zd-Ford,Genk-Zuid-L.O.-Ford,Genk-Zuid-L.O.-Ford,Genk-Zuid-L.O.-Ford,Genk-Zuid-L.O.-Ford,Station,Station,Gare
1,b'\x01\x01\x00\x00\x00\r\to\xbe\xd6\xd5\x11@\x...,b'\x01\x01\x00\x00\x00\r\to\xbe\xd6\xd5\x11@\x...,275,BE00275,GCRA,CHARLEROI-AT,CHARLEROI-AT,CHARLEROI-A.T.,CHARLEROI-A.T.,Charleroi-AT,Charleroi-AT,Charleroi-A.T.,Charleroi-A.T.,Charleroi-A.T.,Charleroi-A.T.,Dienstinstallatie,Service installation,Installation de service
2,"b'\x01\x01\x00\x00\x00>\x84\x92P\xf8,\x11@\x15...","b'\x01\x01\x00\x00\x00>\x84\x92P\xf8,\x11@\x15...",1748,BE01748,VOIL1,V.OILTANK1,V.OILTANK1,VERB.OILTANKING 1,VERB.OILTANKING 1,V.Oiltank1,V.Oiltank1,Verb.Oiltanking 1,Verb.Oiltanking 1,Verb.Oiltanking 1,Verb.Oiltanking 1,Verbinding,Connection,Raccordement
3,b'\x01\x01\x00\x00\x00/J\x7f\xef4)\x11@o\xf1\x...,b'\x01\x01\x00\x00\x00/J\x7f\xef4)\x11@o\xf1\x...,1749,BE01749,VOIL2,V.OILTANK2,V.OILTANK2,VERB.OILTANKING 2,VERB.OILTANKING 2,V.Oiltank2,V.Oiltank2,Verb.Oiltanking 2,Verb.Oiltanking 2,Verb.Oiltanking 2,Verb.Oiltanking 2,Verbinding,Connection,Raccordement
4,"b'\x01\x01\x00\x00\x00\x93\xbc\xb4\xbeF""\x11@7...","b'\x01\x01\x00\x00\x00\x93\xbc\xb4\xbeF""\x11@7...",1751,BE01751,VIBR,V.IBR,V.IBR,VERB.IBR,VERB.IBR,V.IBR,V.IBR,Verb.IBR,Verb.IBR,Verb.IBR,Verb.IBR,Verbinding,Connection,Raccordement

In [35]:
df = pd.read_parquet(DATA_DIR / "monthly_punctuality_agg.parquet")
df.head()

,month,date,lijn,plaats,lieu,place,aard_van_incident,description_de_l_incident,incident_desciption,min_delay,sup
0,2026-02-01,2026-02-24,36,TIENEN,TIENEN,TIENEN,Kabeldiefstal,Vol de câbles,Cable theft,1142,3
1,2026-02-01,2026-02-23,96,HALLE,HALLE,HALLE,Storing seininrichting,Dérangement à la signalisation,Disturbance with signalling,1322,38
2,2026-02-01,2026-02-17,96,MONS,MONS,MONS,Schade treinmaterieel,Avarie matériel roulant,Damage rolling stock,2514,278
3,2026-02-01,2026-02-16,161A,BRUSSEL-SCHUMAN,BRUSSEL-SCHUMAN,BRUSSEL-SCHUMAN,Schade treinmaterieel,Avarie matériel roulant,Damage rolling stock,1827,72
4,2026-02-01,2026-02-09,124,LILLOIS,LILLOIS,LILLOIS,Persoonsongeval,Heurt d'une personne,Collision with a person,1370,72

In [36]:
df = pd.read_csv(DATA_DIR / "punctuality_raw_012024.csv")
df.head()

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,THOP1_COD,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,...,DELAY_ARR,DELAY_DEP,CIRC_TYP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP
0,01JAN2024,1813,IC 02,SNCB/NMBS,929,NaN,50A,NaN,13:09:42,NaN,...,NaN,42.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTENDE,NaN,NaN,01JAN2024,NaN,01JAN2024
1,01JAN2024,1813,IC 02,SNCB/NMBS,210,=,50A,13:22:17,13:25:20,13:22:00,...,17.0,20.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BRUGGE,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
2,01JAN2024,1813,IC 02,SNCB/NMBS,931,D,50A,13:29:18,13:29:18,13:28:00,...,78.0,78.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTKAMP,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
3,01JAN2024,1813,IC 02,SNCB/NMBS,127,P,50A,13:31:59,13:31:59,13:31:00,...,59.0,59.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BEERNEM,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
4,01JAN2024,1813,IC 02,SNCB/NMBS,797,D,50A,13:33:57,13:33:57,13:33:00,...,57.0,57.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,MARIA-AALTER,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024

## 3. Concaténation des 24 datasets mensuels en un seul datasets annuels ##

Les 24 datasets de données mensuelles brutes sont concaténées d'abord en datasets annuels, puis en un dataset unique.<br>
Ce dataset servira de source à la fact table de la data warehouse.

### 3.1. Concaténation en 2 datasets annuels ###

In [ ]:
# Placer dans des listes les paths des datasets de ponctualité mensuels et les trier
files_2024 = list(DATA_DIR.glob("punctuality_raw_*2024.csv"))
files_2024.sort()

files_2025 = list(DATA_DIR.glob("punctuality_raw_*2025.csv"))
files_2025.sort()

# Concaténer les 12 dataframes en un seul dataframe annuel pour 2024 en passant les éléments des listes de paths en paramètres de pd.read_csv()
df_punctuality_raw_2024 = pd.concat(
    (pd.read_csv(f) for f in files_2024),
    ignore_index=True
)
df_punctuality_raw_2024.head()

# Idem pour 2025
df_punctuality_raw_2025 = pd.concat(
    (pd.read_csv(f) for f in files_2025),
    ignore_index=True
)
df_punctuality_raw_2025.head()

# Exporter ces dataframes sous format .parquet dans le répertoire de staging
DATA_INT_DIR = Path("../data/intermediate/")

df_punctuality_raw_2025.to_parquet(DATA_INT_DIR / "punctuality_raw_2025.parquet")
df_punctuality_raw_2024.to_parquet(DATA_INT_DIR / "punctuality_raw_2024.parquet")

### 3.2. Vérification de l'export des deux fichiers ###

In [ ]:
df_punct_2024 = pd.read_parquet(DATA_INT_DIR / "punctuality_raw_2024.parquet")
df_punct_2024.head()

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,THOP1_COD,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,...,DELAY_ARR,DELAY_DEP,CIRC_TYP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP
0,01JAN2024,1813,IC 02,SNCB/NMBS,929,NaN,50A,NaN,13:09:42,NaN,...,NaN,42.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTENDE,NaN,NaN,01JAN2024,NaN,01JAN2024
1,01JAN2024,1813,IC 02,SNCB/NMBS,210,=,50A,13:22:17,13:25:20,13:22:00,...,17.0,20.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BRUGGE,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
2,01JAN2024,1813,IC 02,SNCB/NMBS,931,D,50A,13:29:18,13:29:18,13:28:00,...,78.0,78.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTKAMP,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
3,01JAN2024,1813,IC 02,SNCB/NMBS,127,P,50A,13:31:59,13:31:59,13:31:00,...,59.0,59.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BEERNEM,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024
4,01JAN2024,1813,IC 02,SNCB/NMBS,797,D,50A,13:33:57,13:33:57,13:33:00,...,57.0,57.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,MARIA-AALTER,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024

In [5]:
df_punct_2025 = pd.read_parquet(DATA_INT_DIR / "punctuality_raw_2025.parquet")
df_punct_2025.head()

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,THOP1_COD,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,...,DELAY_DEP,CIRC_TYP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,OP1_COD
0,01JAN2025,3117,IC 31,SNCB/NMBS,259,NaN,124,NaN,17:05:40,NaN,...,40.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,CHARLEROI-CENTRAL,NaN,NaN,01JAN2025,NaN,01JAN2025,NaN
1,01JAN2025,3117,IC 31,SNCB/NMBS,791,=,124,17:09:50,17:11:27,17:10:00,...,27.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,MARCHIENNE-AU-PONT,124,01JAN2025,01JAN2025,01JAN2025,01JAN2025,NaN
2,01JAN2025,3117,IC 31,SNCB/NMBS,1018,P,124,17:14:29,17:14:29,17:14:00,...,29.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,ROUX,124,01JAN2025,01JAN2025,01JAN2025,01JAN2025,NaN
3,01JAN2025,3117,IC 31,SNCB/NMBS,286,D,124,17:15:39,17:15:39,17:15:00,...,39.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,COURCELLES-MOTTE,124,01JAN2025,01JAN2025,01JAN2025,01JAN2025,NaN
4,01JAN2025,3117,IC 31,SNCB/NMBS,768,=,124,17:19:02,17:20:18,17:19:00,...,18.0,1,IC 31: CHARLEROI-CENTRAL -> ANTWERPEN-CENTRAAL,LUTTRE,124,01JAN2025,01JAN2025,01JAN2025,01JAN2025,NaN

### 3.3. Concaténation, export et vérification de l'export du dataset de ponctualité brut ###

In [7]:
# Concaténation
df_punctuality_raw = pd.concat([df_punct_2024, df_punct_2025], ignore_index=True)

In [8]:
# Export
df_punctuality_raw.to_parquet(DATA_INT_DIR / "punctuality_raw.parquet")

In [ ]:
# Vérification
df = pd.read_parquet(DATA_INT_DIR / "punctuality_raw.parquet")
df.head()

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,THOP1_COD,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,...,DELAY_DEP,CIRC_TYP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,OP1_COD
0,01JAN2024,1813,IC 02,SNCB/NMBS,929,NaN,50A,NaN,13:09:42,NaN,...,42.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTENDE,NaN,NaN,01JAN2024,NaN,01JAN2024,NaN
1,01JAN2024,1813,IC 02,SNCB/NMBS,210,=,50A,13:22:17,13:25:20,13:22:00,...,20.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BRUGGE,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024,NaN
2,01JAN2024,1813,IC 02,SNCB/NMBS,931,D,50A,13:29:18,13:29:18,13:28:00,...,78.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,OOSTKAMP,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024,NaN
3,01JAN2024,1813,IC 02,SNCB/NMBS,127,P,50A,13:31:59,13:31:59,13:31:00,...,59.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,BEERNEM,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024,NaN
4,01JAN2024,1813,IC 02,SNCB/NMBS,797,D,50A,13:33:57,13:33:57,13:33:00,...,57.0,1,IC 02: OOSTENDE -> ANTWERPEN-CENTRAAL,MARIA-AALTER,50A,01JAN2024,01JAN2024,01JAN2024,01JAN2024,NaN